server:
  port: 36257

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.springframework.web: INFO

auth-service:
  host: host.docker.internal
  port: 36260

user-service:
  host: users
  port: 36260

vehicle-service:
  host: vehicles
  port: 36258

rides-service:
  host: rides
  port: 36259
